services:
  postgres:
    image: postgres:15
    container_name: energybroker_postgres
    environment:
      POSTGRES_DB: energybroker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - energybroker_net

  redis:
    image: redis:7
    container_name: energybroker_redis
    ports:
      - "6379:6379"
    networks:
      - energybroker_net

  energybroker-service:
    build: .
    container_name: energybroker_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energybroker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - energybroker_net

volumes:
  pgdata:

networks:
  energybroker_net:
